vim.opt.number = true
vim.opt.autoindent = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smarttab = true
vim.opt.autoindent = true
vim.opt.wrap = false
vim.opt.smartcase = true
vim.opt.incsearch = true
vim.opt.showtabline = 2
vim.opt.ambiwidth = 'single'
vim.opt.termguicolors = true
vim.opt.colorcolumn = "80"
vim.opt.hls = true
vim.opt.signcolumn = 'yes'
vim.g.mapleader = ' '
