vim.keymap.set('n', '<Leader>r', ':source $XDG_CONFIG_HOME/nvim/init.lua<CR>')
vim.keymap.set('n', '<Leader>l', '$', { silent = true })
vim.keymap.set('n', '<Leader>h', '0', { silent = true })
vim.keymap.set('v', '<Leader>l', '$', { silent = true })
vim.keymap.set('v', '<Leader>h', '0', { silent = true })
vim.keymap.set('n', 'j', 'gj', { silent = true })
vim.keymap.set('n', 'k', 'gk', { silent = true })
vim.keymap.set('v', 'j', 'gj', { silent = true })
vim.keymap.set('v', 'k', 'gk', { silent = true })
vim.keymap.set('n', '<Leader>y', 'byw', { silent = true })
vim.keymap.set('n', '<Leader>v', 'bve', { silent = true })

vim.keymap.set('i', 'jj', '<ESC>', { silent = true })
vim.keymap.set('n', '<Leader>w', ':w<CR>', { silent = true })
vim.keymap.set('n', 'qq', ':q<CR>', { silent = true })
vim.keymap.set('n', '<Esc><Esc>', ':<C-u>set nohlsearch!<CR>', { silent = true })

vim.keymap.set('i', '<F1>', '<C-R>=strftime("%Y-%m-%d")<CR>', { silent = true })
vim.keymap.set('i', '<F2>', '<C-R>=strftime("%Y-%m-%d (%a)")<CR>', { silent = true })
vim.keymap.set('n', '<F3>', ':echo expand("%:p")<CR>', { silent = false })
