# ----.clang-format----
# ref http://yasuharu519.hatenablog.com/entry/2015/12/13/210825
# --------------------
AccessModifierOffset: -2
AlignAfterOpenBracket: true
AlignEscapedNewlinesLeft: true
AlignTrailingComments: false
AlignConsecutiveAssignments: true
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: 'None'
#ifでワンラインにするかどうか
AllowShortIfStatementsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: false
AlwaysBreakBeforeMultilineStrings: true
AlwaysBreakTemplateDeclarations: false
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: 'None'
BreakBeforeBraces: 'Allman'
ContinuationIndentWidth: 2
ColumnLimit: 0
Cpp11BracedListStyle: true
IndentCaseLabels: false
IndentWidth: 2
# IndentWrappedFunctionNames
KeepEmptyLinesAtTheStartOfBlocks: false
MaxEmptyLinesToKeep: 2
NamespaceIndentation: 'None'
PointerAlignment: 'Right'
SpaceAfterCStyleCast: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: 'ControlStatements'
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 4
SpacesInCStyleCastParentheses: true
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard: 'Cpp11'
TabWidth: 4
UseTab: 'Never'
