[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
    let g:deoplete#sources#jedi#python_path = '/usr/local/bin/python3'
'''

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'tomasr/molokai'