# ddc.vim遅延読み込み用のdein.toml
# ddc.vim {{{
[[plugins]]
hook_post_source = '''
call ddc#custom#patch_global('completionMenu', ['pum.vim'])
call ddc#custom#patch_global('sources', [
 \ 'around',
 \ 'vim-lsp',
 \ 'file'
 \ ])
call ddc#custom#patch_global('sourceOptions', {
 \ '_': {
 \   'matchers': ['matcher_head'],
 \   'sorters': ['sorter_rank'],
 \   'converters': ['converter_remove_overlap']
 \ },
 \ 'around': {
 \   'mark': 'around'
 \ },
 \ 'vim-lsp': {
 \   'mark': 'LSP', 
 \   'matchers': ['matcher_head'],
 \   'forceCompletionPattern': '\.|:|->|"\w+/*'
 \ },
 \ 'file': {
 \   'mark': 'file',
 \   'isVolatile': v:true, 
 \   'forceCompletionPattern': '\S/\S*'
 \ }})
call ddc#enable()
inoremap <C-n> <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p> <Cmd>call pum#map#insert_relative(-1)<CR>
'''
on_event = 'InsertEnter'
repo = 'Shougo/ddc.vim'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-around'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/pum.vim'

[[plugins]]
on_source = 'ddc.vim'
repo = 'LumaKernel/ddc-file'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-nextword'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-sorter_rank'

# }}}

# nvim-lsconfig {{{
# LSP (Language Server Protocol)
[[plugins]]
hook_source = '''
call popup_preview#enable()
'''
on_source = 'ddc.vim'
repo = 'matsui54/denops-popup-preview.vim'

[[plugins]]
hook_source = '''
call signature_help#enable()
" let g:lsp_signature_help_enabled = 0
'''
on_source = 'ddc.vim'
repo = 'matsui54/denops-signature_help'

# }}}
# vim:set fileencoding=utf-8 fileformat=unix foldmethod=marker:
