[[plugins]]
repo = 'williamboman/mason.nvim'
hook_add = '''
lua <<EOF
  require("mason").setup()
EOF
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = [
  "neovim/nvim-lspconfig",
  "williamboman/mason.nvim",
]
hook_add='''
lua <<EOF
  require("mason-lspconfig").setup()
  require("mason-lspconfig").setup_handlers {
    function (server_name)
      require("lspconfig").pylsp.setup{
        settings = {
            pylsp = {
                plugins = {
                    flake8 = {enabled = true},
                    autopep8 = {enabled = true},
                    mccabe = {enabled = false},
                    pycodestyle = {enabled = false},
                    pyflakes = {enabled = false},
                    pylint = {enabled = true},
                    yapf = {enabled = true}
                }
            }
        }
      }
    end,
  }
EOF
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = "jose-elias-alvarez/null-ls.nvim"
depends = ['mason.nvim']

[[plugins]]
repo = "jayp0521/mason-null-ls.nvim"
depends = [
    'mason.nvim',
    'null-ls.nvim'
]
hook_add = '''
lua <<EOF
require("null-ls").setup()
require("mason-null-ls").setup({
    automatic_setup = true,
})
EOF
'''

